### ISSUE TITLE
[Azure DevOps] Need more indications on installing process

### ISSUE THREAD

**Issue by masonyc** [jonathanpeppers/boots#11]
**Problem**
When I added install Xamarin.Android Task to my windows build definition, it seems like it is running forever on the install task with no indications on whats the current status after line 33 in the attached screenshot.

**Platform**
Build using windows-2019

**Screenshot**
![image](https://user-images.githubusercontent.com/18006944/63230248-4b723100-c25e-11e9-8e75-ccbfe577e316.png)

**Comment by jonathanpeppers** [comment]
What is the full log when the build finishes?

It took about 10 minutes on the last build in this repo: https://jopepper.visualstudio.com/Jon%20Peppers%20OSS/_build/results?buildId=313&view=logs

Compared to 21 seconds on Mac...

**Comment by masonyc** [comment]
> What is the full log when the build finishes?
> 
> It took about 10 minutes on the last build in this repo: https://jopepper.visualstudio.com/Jon%20Peppers%20OSS/_build/results?buildId=313&view=logs
> 
> Compared to 21 seconds on Mac...

I actually haven't tried to let the build finish. The last build lasts for 7m 15s and I cancelled it because we are on the free version of DevOps and I was not sure how long it would take at that time.

**Comment by jonathanpeppers** [comment]
I don’t think we have a way for vsixinstaller.exe to run any faster, but you might consider building on Mac, if you need to provision Xamarin and build times are a concern for you.

You might also check you are using the 2019 pool, it might help, not sure.

**Comment by masonyc** [comment]
> I don’t think we have a way for vsixinstaller.exe to run any faster, but you might consider building on Mac, if you need to provision Xamarin and build times are a concern for you.
> 
> You might also check you are using the 2019 pool, it might help, not sure.

Thanks, I will try it on mac.
