### ISSUE TITLE
Update to use .NET Core 3

### ISSUE THREAD

**Issue by jamesmontemagno** [jonathanpeppers/boots#19]
This is now the default that is installed with 16.3, else we have to manually install 2.2.x

**Comment by jonathanpeppers** [comment]
I played around with this on: https://github.com/jonathanpeppers/boots/issues/19

It looks like I need to push a new NuGet package that is built multi-targeting both `netcoreapp2.0` and `netcoreapp3.0`.

**Comment by jonathanpeppers** [comment]
Let me know if the latest release doesn't solve it: https://github.com/jonathanpeppers/boots/releases/tag/1.0.1.386

I basically just included `netcoreapp3.0` in the NuGet package and it seems to work, thanks.
