### ISSUE TITLE
Clarify software compatibility

### ISSUE THREAD

**Issue by bruno-garcia** [jonathanpeppers/boots#22]
Firstly thanks for creating this tool to help us out.

I'm trying to get `boots` to work with some CI services we usually use. Mainly Travis and Appveyor.

From what I've noticed `boots` is not compatible with the travis image `xcode9.2`. It simply can'y install as the [log of this commit](https://github.com/getsentry/symbol-collector/commit/06f3e852724851f0ff06b51227635a09eaf83ef2) shows:

```
$ dotnet tool install --global boots

Welcome to .NET Core 3.0!

---------------------

SDK Version: 3.0.100

----------------

Explore documentation: https://aka.ms/dotnet-docs

Report issues and find source on GitHub: https://github.com/dotnet/core

Find out what's new: https://aka.ms/dotnet-whats-new

Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https

Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Write your first app: https://aka.ms/first-net-core-app

--------------------------------------------------------------------------------------

bol binding failed: Symbol not found: _utimensat

  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Native.dylib

  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat

  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Native.dylib

  Expected in: /usr/lib/libSystem.B.dylib

The tool package could not be restored.

Tool 'boots' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.

* A package by this name was found, but it was not a .NET Core tool.

* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.

* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

The command "dotnet tool install --global boots" exited with 1.
```

Sadly Travis-CI is limited in terms of JDK support with newer versions of `xcode`. So if I bump xcode [like in this build](https://travis-ci.com/getsentry/symbol-collector/builds/139064582), `boots` installs correctly but building Xamarin.Android fails due to JDK11.

I've tried to pin the jdk version in different ways (can be seen in the follow up builds for that project) but none worked.

the `android` image on travis is based on Linux, which unfortunately has no `boots` support.

Trying macOS on appveyor also didn't work out.

Culprit seems to be: `A fatal error occurred. The required library libhostfxr.dylib could not be found.` but the [relevant part of the log of the builds is](https://ci.appveyor.com/project/sentry/symbol-collector/builds/29266580):

```
Build started
git clone -q --branch=feat/appveyor https://github.com/getsentry/symbol-collector.git /Users/appveyor/projects/symbol-collector
git checkout -qf a1f959fc7899e4d7aafc59f5ff2e17cf137723c2
Running "install" scripts
export PATH="$PATH:/Users/appveyor/.dotnet/tools"
dotnet tool install --global boots
You can invoke the tool using the following command: boots
Tool 'boots' (version '1.0.1.386') was successfully installed.
boots https://download.mono-project.com/archive/6.0.0/macos-10-universal/MonoFramework-MDK-6.0.0.313.macos10.xamarin.universal.pkg
A fatal error occurred. The required library libhostfxr.dylib could not be found.
If this is a self-contained application, that library should exist in [/Users/appveyor/.dotnet/tools/.store/boots/1.0.1.386/boots/1.0.1.386/tools/netcoreapp3.0/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/local/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
Command exited with code 131
Build failed
```

Now the question: Is there a compatibility matrix somewhere?

it's clear only macOS and Windows are supported, but what version of xcode does it require on macOS? Any thoughts why the second (appveyor) build is faling?
Thanks.

**Comment by jonathanpeppers** [comment]
I think what you are seeing here is actually .NET Core compatibility on macOS.

### First issue on TravisCI

```
SDK Version: 3.0.100
...
bol binding failed: Symbol not found: _utimensat
```

I would guess that .NET Core 3.0 doesn't work with Xcode 9.2? They say:
```
NET Core 3.0 is supported on macOS High Sierra (version 10.13) and later.
```
So maybe Xcode is also involved?

While .NET Core 2.2 supports older:
```
. NET Core 2.2 is supported on macOS Sierra (version 10.12) and later versions.
```

### Second issue on AppVeyor

The second error you might be able to use this workaround: https://github.com/jonathanpeppers/boots/blob/b69065db38f8a2685a3fbe5b953dc1c80dd7720a/samples/HelloForms.Android/appcenter-pre-build.sh#L8-L11

### Another idea

All the problems here just appear to be using .NET Core in general 🤦‍♂ on these CI machines.

If `boots` is too hard to get running in these enviroments, you might consider just doing:

```
wget https://download.mono-project.com/archive/6.0.0/macos-10-universal/MonoFramework-MDK-6.0.0.313.macos10.xamarin.universal.pkg -O mono.pkg
sudo installer -pkg mono.pkg -target / -verbose
```

I should look into making a FAQ with these ideas listed, and maybe setup this repo on TravisCI and AppVeyor.

**Comment by bruno-garcia** [comment]
Thanks for clarifying this. And also for replying on my [issue](https://github.com/xamarin/xamarin-android/issues/3996#issuecomment-562590617) in the Xamarin repo.
