### ISSUE TITLE
Find correct paths to specific versions of packages

### ISSUE THREAD

**Issue by Brosten** [jonathanpeppers/boots#23]
I'm new to boots, but I have trouble finding the correct path to the package I want.
I see that my mac installation has Xamarin iOS version 13.8.2.2
I know my code compiles against it, so I want to use this exact version in Azure Dev Ops. But from the link in this Projects readme, I find it pretty hard to find the exact download-path to 13.8.2.2 package. Could it be clerified in some way?

**Comment by jonathanpeppers** [comment]
I am on the Xamarin.Android team, and we specifically make these URLs easy to find. When we write the release notes, we make an `aka.ms` URL. On iOS, maybe they have a way I don't know?

Their branch naming, such as `d16-3` would map to Visual Studio 2019 16.3. But in your case the version number doesn't match:

![image](https://user-images.githubusercontent.com/840039/70629623-e61cc400-1bef-11ea-9341-5ef66fd7ecf6.png)

So then I looked at the `xcode11.3` branch and found this commit:

https://github.com/xamarin/xamarin-macios/commit/44c08f2ca31c586023a70f9a09c6971a3c439a1c

Which has a notarized build:

https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11.3/44c08f2ca31c586023a70f9a09c6971a3c439a1c/1/package/notarized/xamarin.ios-13.8.2.2.pkg

You can use the CDN version of this URL as well: 

https://bosstoragemirror.azureedge.net/wrench/jenkins/xcode11.3/44c08f2ca31c586023a70f9a09c6971a3c439a1c/1/package/notarized/xamarin.ios-13.8.2.2.pkg

@mandel-macaque or @dalexsoto is this the easiest way to find these?

**Comment by jrr** [comment]
When you install Xamarin.iOS via Visual Studio for Mac's UI, does it pull down a .pkg? Where's the canonical source of truth for the version that Visual Studio for Mac uses?

Is there anywhere else in the community that has solved headless installation of latest-stable Xamarin.iOS? (perhaps the VSTS or AppCenter teams?)

**Comment by jonathanpeppers** [comment]
@jrr you might be interested in #25 I just got this working today.

I will hopefully ship this in a preview soon.

**Comment by jonathanpeppers** [comment]
@Brosten and @jrr I think you should be able to use the new features in the latest release for what you need here:

https://github.com/jonathanpeppers/boots/releases/tag/1.0.2.421

```
dotnet tool install --global boots --version 1.0.2.421
boots --stable Mono
boots --preview XamarinAndroid
boots --preview XamariniOS
boots --preview XamarinMac
```

It doesn't pin to a version, but grabs the latest that VS offers. You might read the details of how it works if you need to find a specific URL:

* https://github.com/jonathanpeppers/boots/blob/e0b99da50bc7d5eaa7a7c8714616a74dab180673/Boots.Core/MacUrlResolver.cs
* https://github.com/jonathanpeppers/boots/blob/e0b99da50bc7d5eaa7a7c8714616a74dab180673/Boots.Core/WindowsUrlResolver.cs

**Comment by jrr** [comment]
This is fantastic, @jonathanpeppers , thanks!

**Comment by cosminstirbu** [comment]
Hello,

First of all thanks for working on this tool, I feel that build repeatability and  Xamarin.iOS / Xamarin.Android / Mono version pinning has historically been neglected and undocumented.

However - finding the right URLs for Xamarin.iOS / Xamarin.Android is really difficult. Linking them to a Visual Studio release assumes that they have the same release cadence, which is not been the case - there were many times when there have been new Xamarin.iOS / Xamarin.Android without a Visual Studio release.

Ideally for any given preview / stable build we should be able to easily find the corresponding URLs in https://docs.microsoft.com/en-us/xamarin/ios/release-notes/ / https://docs.microsoft.com/en-us/xamarin/android/release-notes/.

If for instance I want to download Xamarin.iOS 13.8.3.0 - I can't find the commit reference to grab the notarized build.

Similarly if I want to download Xamarin.Android 10.1.3.7 - I can find the tag/release on Github (https://github.com/xamarin/xamarin-android/releases/tag/v10.1.3.7) but can't find the download link.

Until you fix these issues, I'd say the tool itself is quite limited.

Thanks,
Cosmin

**Comment by jonathanpeppers** [comment]
@cosminstirbu I think you are asking me to change the Visual Studio release process for multiple teams. 👀 

This little stormtrooper has little to no control over the will of the empire.

![storm fail](https://media.giphy.com/media/WUFgopvwap3AA/giphy.gif)

**Comment by cosminstirbu** [comment]
Not really - I'm just asking for download links next to each version (both stable and previews) in the release notes (or a easy way to find them starting from the release notes)

https://docs.microsoft.com/en-us/xamarin/ios/release-notes/
https://docs.microsoft.com/en-us/xamarin/android/release-notes/

One is owned by Xamarin.Android team (where I'm sure you have enough influence) and the other is owned by Xamarin.iOS team where I'm sure you have some solid connections :grinning:.

**Comment by brendanzagaeski** [comment]
For Xamarin.Android, since I work on those notes myself, I'll plan to start including additional links in the GitHub release pages for Release versions.

As I was looking up info for Xamarin.Android SDK version 10.2.0.100, it occurred to me that the recommended approach for a Windows continuous build environment would likely be to use the BuildTools installer from the [Visual Studio release history page](https://docs.microsoft.com/visualstudio/releases/2019/history). As far as I know, there isn't yet a similar installer for Visual Studio for Mac, so using the individual *.pkg* installer packages is probably the best option at the moment. I updated the Xamarin.Android SDK version 10.2.0.100 GitHub release notes to include the relevant links.

For Xamarin.iOS, I think the steps Jonathan Peppers mentioned in <https://github.com/jonathanpeppers/boots/issues/23#issuecomment-564570940> would work? For example, if I navigate to <https://github.com/xamarin/xamarin-macios/tags>, click on a commit hash for one of the tags, and then click on the status icon for the commit, I see a **PKG-Xamarin.iOS-notarized** entry in the list. If I replace the domain in that link with bosstoragemirror.azureedge.net to get it from the CDN, it seems to work OK. (xamarin-ios-13.8.3.0 is currently on the second page of the tags list.)

**Comment by cosminstirbu** [comment]
Thanks for following up on this - this is a good start and it easily got me going.

For some reason when I initially looked at the tags on the Xamarin.iOS project I've noticed only the macOS tags, but actually there are all the tags and I can use that to grab the notarised packaged.

Also the link on the Xamarin.Android 10.2.0.100 release notes helped.

For anyone interested, this is my .yml

```
steps:
- task: CmdLine@2
  displayName: 'Install and Pin Mono and Xamarin versions'
  inputs:
    script: |
      dotnet tool update --global boots --version 1.0.2.421
      boots https://download.mono-project.com/archive/6.8.0/macos-10-universal/MonoFramework-MDK-6.8.0.105.macos10.xamarin.universal.pkg
      boots https://download.visualstudio.microsoft.com/download/pr/8f94ca38-039a-4c9f-a51a-a6cb33c76a8c/aa46188c5f7a2e0c6f2d4bd4dc261604/xamarin.android-10.2.0.100.pkg
      boots https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-5-xcode11.4/30e8706b4fd666503870d5f2b481584d5fe06a1d/1/package/notarized/xamarin.ios-13.14.1.39.pkg
      readlink /Library/Frameworks/Mono.framework/Versions/Current
      readlink /Library/Frameworks/Xamarin.iOS.framework/Versions/Current
      readlink /Library/Frameworks/Xamarin.Android.framework/Versions/Current
```

I've added those readlinks to make sure that indeed the current versions are correctly linked :D

Thanks,
Cosmin
