### ISSUE TITLE
App Center Xamarin.iOS - nuget not found after running boots

### ISSUE THREAD

**Issue by dylanberry** [jonathanpeppers/boots#33]
Hi Jonathan,

I'm running into an issue where after setting up `appcenter-post-clone.sh`, App Center is now failing to find nuget (`/bin/bash: nuget: command not found`).

This is the relevant output (let me know if you would like more):
```
##[section]Starting: Restore Nuget
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
[command]/bin/bash -c nuget restore 'AmazingMobile.sln' -DisableParallelProcessing
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4671) Warning: Use Cipheriv for counter mode of aes-256-ctr
/bin/bash: nuget: command not found
##[error]/bin/bash failed with return code: 127
##[error]/bin/bash failed with error: /bin/bash failed with return code: 127
##[section]Finishing: Restore Nuget
```

Here's my script:
```
#!/usr/bin/env bash
# App Center custom build scripts: https://aka.ms/docs/build/custom/scripts

export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

dotnet tool install --global boots

# Workaround instead of restarting shell
# see: https://github.com/dotnet/cli/issues/9114#issuecomment-494226139
export PATH="$PATH:~/.dotnet/tools"
export DOTNET_ROOT="$(dirname "$(readlink "$(command -v dotnet)")")"

boots --preview Mono
boots --preview XamariniOS
```

I have also tried to setup an alias, with no joy (same error/log output):
```
# set an alias for nuget
alias nuget="/Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget"
```

Thanks for your awesome work on boots and Xamarin Android!

Cheers,
Dylan

**Comment by jonathanpeppers** [comment]
This doesn’t seem like an issue with boots? NuGet is failing? Does the NuGet command work if you don’t install/update Mono?

I would consider migrating to PackageReference instead of using packages.config.

Then you can just do:

    msbuild AmazingMobile.sln /restore

The /restore flag will automatically restore NuGets, but it doesn’t work with packages.config.

**Comment by dylanberry** [comment]
It has something to do with the mono install for sure, when I comment out `boots --preview Mono` the build completes successfully. 

I am using `PackageReference` in my projects, the nuget restore appears to be a part of the build definition used by App Center. I'm not explicitly scripting anything to restore packages.

This is pure App Center (from the logs I pasted):
```
##[section]Starting: Restore Nuget
```

**Comment by jonathanpeppers** [comment]
I don't see a way to turn off the NuGet restore in App Center.

Maybe try setting the latest they offer:

![image](https://user-images.githubusercontent.com/840039/77317555-6bc50b00-6cd9-11ea-8be2-a707095e1dc2.png)

It's probably worth filing an issue with them: https://github.com/microsoft/appcenter/issues

Maybe they have an undocumented way to skip the NuGet restore? That would speed up your build, too.

**Comment by dylanberry** [comment]
Yeah, I'm using the latest from the UI, but I'm building iOS, I need Xamarin.iOS 13.14/Mono 6.8, app center only has options to build with Xamarin.iOS 13.10/Mono 6.6.

I'll get an issue filed. For now, I have moved the boots scripts to `appcenter-post-clone.sh` which runs after the "Restore Nuget" task. Was there a reason why the docs have the boots commands running in  `appcenter-post-clone.sh`?

**Comment by jonathanpeppers** [comment]
Somehow `appcenter-pre-build.sh` is working in this repo, not sure why? I am using AppCenter with my Microsoft employee account, so maybe I'm on some internal MS instance of it, I'm not sure.

Using either one should be fine, I think this is fine to close?

If you want to take a shot at updating the docs here, I would accept a PR, thanks!
