### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by VladislavAntonyuk** [jonathanpeppers/boots#37]
```
Deleting /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/yn0hvhgu.77w.pkg
* Automatic URL resolving is a new feature. File issues at: https://github.com/jonathanpeppers/boots/issues
Querying https://software.xamarin.com/Service/Updates?v=2&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=0&pv4569c276-1397-4adb-9485-82a7696df22e=0&pvd1ec039f-f3db-468b-a508-896d7c382999=0&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=0&level=Beta
Downloading https://download.visualstudio.microsoft.com/download/pr/2d017781-5514-4802-9dbc-e0f2edfe6f7c/b32ea4d7727a0551d3ad000640243ea5/xamarin.ios-13.18.1.31.pkg
Writing to /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/oaekiab0.8sy.pkg
Deleting /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/oaekiab0.8sy.pkg
An error occurred when executing task 'InstallSoftware'.
----------------------------------------
Teardown
----------------------------------------
Finished running tasks.
Error: One or more errors occurred. ('/usr/bin/sudo' with arguments '/usr/sbin/installer -pkg "/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/oaekiab0.8sy.pkg" -target / -verbose' exited with code 137)
	'/usr/bin/sudo' with arguments '/usr/sbin/installer -pkg "/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/oaekiab0.8sy.pkg" -target / -verbose' exited with code 137
```

**Comment by jonathanpeppers** [comment]
We saw something like this with Xamarin.Forms' build, but we weren't able to figure it out.

Is this running in Cake, can you add `-v diagnostic` to get more logging?

**Comment by VladislavAntonyuk** [comment]
yes, it is a cake Task. I am not sure it is related to the Xamarin.Forms. the issue happens before I try to build the project. 
how can I add v parameter? I use cake as await Boots (Product.XamarinAndroid, ReleaseChannel.Preview);

**Comment by jonathanpeppers** [comment]
The `-v` switch is used when running Cake command-line, so if you have a script like `./build.sh -v Diagnostic -t YourTarget` or `.\build.ps1 -v Diagnostic -t YourTarget`.

**Comment by VladislavAntonyuk** [comment]
https://ci.appveyor.com/project/VladislavAntonyuk/draw-go/builds/32706892/job/q0cfcst9se2nufid

**Comment by jonathanpeppers** [comment]
@VladislavAntonyuk are you using the latest 1.0.2.437 version of `Cake.Boots`?

The log doesn't include the `-dumplog` switch, which was added in https://github.com/jonathanpeppers/boots/pull/36:
```
Querying https://software.xamarin.com/Service/Updates?v=2&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=0&pv4569c276-1397-4adb-9485-82a7696df22e=0&pvd1ec039f-f3db-468b-a508-896d7c382999=0&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=0&level=Beta
Downloading https://download.visualstudio.microsoft.com/download/pr/2d017781-5514-4802-9dbc-e0f2edfe6f7c/b32ea4d7727a0551d3ad000640243ea5/xamarin.ios-13.18.1.31.pkg
Writing to /var/folders/5c/0fwh2vd52hzbpq9xpjsfct740000gn/T/i19coug3.43c.pkg
Deleting /var/folders/5c/0fwh2vd52hzbpq9xpjsfct740000gn/T/i19coug3.43c.pkg
An error occurred when executing task 'InstallSoftware'.
----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Finished running tasks.
Error: System.AggregateException: One or more errors occurred. ('/usr/bin/sudo' with arguments '/usr/sbin/installer -pkg "/var/folders/5c/0fwh2vd52hzbpq9xpjsfct740000gn/T/i19coug3.43c.pkg" -target / -verbose' exited with code 137) ---> System.Exception: '/usr/bin/sudo' with arguments '/usr/sbin/installer -pkg "/var/folders/5c/0fwh2vd52hzbpq9xpjsfct740000gn/T/i19coug3.43c.pkg" -target / -verbose' exited with code 137
  at Boots.Core.AsyncProcess.RunAsync (System.Threading.CancellationToken token) [0x0009b] in <dce3c1633bec4e9aa718b36431577051>:0 
  at Boots.Core.PkgInstaller.Install (System.String file, System.Threading.CancellationToken token) [0x000f9] in <dce3c1633bec4e9aa718b36431577051>:0 
  at Boots.Core.Bootstrapper.Install (System.Threading.CancellationToken token) [0x0022c] in <dce3c1633bec4e9aa718b36431577051>:0 
  at Cake.Boots.BootsAddin.Boots (Cake.Core.ICakeContext context, Product product, ReleaseChannel channel) [0x0009b] in <6742330a51e4403f88f312aed94692e5>:0 
```

**Comment by VladislavAntonyuk** [comment]
I used 1.0.2.421. Updated to the latest version. Waiting for build

**Comment by VladislavAntonyuk** [comment]
https://ci.appveyor.com/project/VladislavAntonyuk/draw-go/builds/32734442/job/s2iwmyf7cuefg5ai

**Comment by jonathanpeppers** [comment]
I tried testing out `AppVeyor` & macOS in this repo: https://github.com/jonathanpeppers/boots/pull/38

Do you see anything I'm doing that is different? I used the `macOS` image, and the cake script is:

https://github.com/jonathanpeppers/boots/blob/92091cc7762b28605a91c26e6c64b8037dbb8bac/Cake.Boots/build.cake#L1-L27

**Comment by VladislavAntonyuk** [comment]
My cake looks a bit different:
```
#addin nuget:?package=Cake.Boots

Task("InstallSoftware")
    .WithCriteria(Argument("CI", false) == true && IsRunningOnUnix())
    .Does(async () =>
    {
        await Boots (Product.Mono, ReleaseChannel.Preview);
        await Boots (Product.XamariniOS, ReleaseChannel.Preview);
        await Boots (Product.XamarinMac, ReleaseChannel.Preview);
        await Boots (Product.XamarinAndroid, ReleaseChannel.Preview);
    });

...
```

**Comment by jonathanpeppers** [comment]
Thank you! Somehow this combination breaks: https://github.com/jonathanpeppers/boots/pull/38/commits/37edbda173cf8f7ef81b97dced7044cb4a7d1be6

I've been trying to track this down and couldn't reproduce it...

**Comment by jonathanpeppers** [comment]
Ok, I figured out what is going on...

If you update Mono, you will need to restart in a new process for the remainder of the build. Otherwise _weird things happen_...

So for example, in https://github.com/jonathanpeppers/boots/pull/38/commits/37edbda173cf8f7ef81b97dced7044cb4a7d1be6 I made a `Mono` Cake target and installed in two steps:
```
./build.sh -t Mono
./build.sh
```
The second Cake build will startup in a new process, using the new Mono that was just installed. Can you try this?

I guess all I can do is document this? I will also try the new [Cake.Tool](https://cakebuild.net/blog/2020/02/cake-v0.37.0-released), as it might be a better option for nowadays: 
```
dotnet tool install Cake.Tool
dotnet-cake build.cake
```

**Comment by VladislavAntonyuk** [comment]
will 
```
dotnet tool install --global Cake.Tool
dotnet-cake build.cake
```
solve the issue?

what if I install it like 
```
dotnet tool install --global boots --version 1.0.2.421
boots --stable Mono
boots --preview XamarinAndroid
boots --preview XamariniOS
boots --preview XamarinMac
```
and than execure
```
./build.sh
```

**Comment by jonathanpeppers** [comment]
Just try installing Mono in a separate step:
```
./build.sh -t Mono
./build.sh
```
That seemed to solve it for me: https://github.com/jonathanpeppers/boots/pull/38/files#diff-28f2ff3107b6e2ee7e5def09af4def7eR7-R13

**Comment by VladislavAntonyuk** [comment]
I decided to use dotnet tool, because I only use it in appveyor, I do not think I need a task in Cake. Thank you for help!
