### ISSUE TITLE
[question] any public links available for newest mono builds as 6.12.0.122

### ISSUE THREAD

**Issue by gsgou** [jonathanpeppers/boots#75]
since mono is moving its CI/CD to AzureDevops
https://github.com/mono/mono/issues/20841
for the newest mono builds as 6.12.0.122 i don't know any public link available
as https://download.mono-project.com/archive/6.12.0/macos-10-universal/
Any hint maybe where to download it? Thanks.

**Comment by jonathanpeppers** [comment]
`@steveisok` is the right person to ask, let me know what he says.

**Comment by gsgou** [comment]
@jonathanpeppers the newer build artifacts are again available, you can close this.
https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.122.macos10.xamarin.universal.pkg
